
/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

 // following example of calibration.h 
/*#define CALIBRATION_H

const int acc_off_x = 6.4322;
const int acc_off_y = 6.7379;
const int acc_off_z = 28.5567;
const float acc_scale_x = 253.999;
const float acc_scale_y = 254.304;
const float acc_scale_z = 249.271;

const int magn_off_x = 67;
const int magn_off_y = -59;
const int magn_off_z = 26;
const float magn_scale_x = 527.652115;
const float magn_scale_y = 569.016790;
const float magn_scale_z = 514.710857;
*/

